### ISSUE TITLE
Minor issue with download link for basic_data.zip

### ISSUE THREAD

**Issue by kanihal** [dalab/deep-ed#1]
I was not able download basic_data.zip from this google drive link https://drive.google.com/drive/u/2/folders/0Bx8d3azIm_ZcRGVkQS1WYkJtcU0.
I think you need to check `allow anyone to download` option in **your** (indicate by /u/2 in url) drive share settings.
or
Replace the link with account independent file link https://drive.google.com/uc?id=0Bx8d3azIm_ZcbHMtVmRVc1o5TWM&export=download
This works.

**Comment by octavian-ganea** [comment]
Solved. Thx.
