### ISSUE TITLE
unknown wikiids

### ISSUE THREAD

**Issue by lephong** [dalab/deep-ed#10]
After training entity embeddings, looking at all_candidate_ents_ed_rltd_datasets_RLTD.t7 I found about 1563 wikiids that can't be mapped to any names. For instance 

694
1286
2242
4705
9503
9568
13877
14795
17434
18129
19808
22356
26891

Do you have any idea why?

**Comment by octavian-ganea** [comment]
I removed all wikipages that are either list or disambiguation pages. Your pages seem to be either invalid or in this category : https://en.wikipedia.org/w/?curid=13877

**Comment by lephong** [comment]
I see. Thanks!
