### ISSUE TITLE
Program bug

### ISSUE THREAD

**Issue by LMY-nlp0701** [dalab/deep-ed#15]
Hello!  Sorry to disturb you.
I encountered some programs bug and I hope you can help me solve this problem.

### **Program bug**
I think I have already done the preliminary work.
I made tenth steps：10.Generate all entity disambiguation datasets in a CSV format needed in our training stage:
As shown in the picture:
![step_10](https://user-images.githubusercontent.com/33420219/47604557-0f02e980-da2e-11e8-8eb5-497b9b258ca6.png)

I ran the code and got the following results, but I met some bug.
As shown in the picture:
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/33420219/47604607-b8e27600-da2e-11e8-9246-734bcf096db8.png">
<img width="1280" alt="2" src="https://user-images.githubusercontent.com/33420219/47604613-c1d34780-da2e-11e8-8d99-05ed5dae4c0e.png">
<img width="1279" alt="3" src="https://user-images.githubusercontent.com/33420219/47604617-c5ff6500-da2e-11e8-9cc5-0dcf842f2108.png">

Thank you!

**Comment by octavian-ganea** [comment]
This likely means that the file opened in line 182 does not exist. Can you verify that the file at path mentioned in L182 does really exist ?

**Comment by LMY-nlp0701** [comment]
Hi, I downloaded, unpacked and uploaded basic_data again.
After my investigation step by step, I find the problem is **gen_test_ace('wikipedia')**（data_gen/gen_test_train_data/gen_ace_msnbc_aquaint_csv.lua   line:202）

When I annotate this line(202 line)
![0](https://user-images.githubusercontent.com/33420219/47999002-08febe00-e13c-11e8-8855-cd242c227c01.png)


### **Run step 10, successful operation is as follows:**
![1](https://user-images.githubusercontent.com/33420219/47998878-ac030800-e13b-11e8-9d9b-868ac0547b23.jpg)
![2](https://user-images.githubusercontent.com/33420219/47998888-b1605280-e13b-11e8-9f78-b9032ab27d85.jpg)
![3](https://user-images.githubusercontent.com/33420219/47998893-b58c7000-e13b-11e8-893b-403bfc1bc5f1.jpg)
![4](https://user-images.githubusercontent.com/33420219/47998901-b8876080-e13b-11e8-8147-48314fbe96ef.jpg)

I think the program runs successfully, because the generated files and sizes are consistent with those described later.
![5](https://user-images.githubusercontent.com/33420219/47999016-1b78f780-e13c-11e8-9149-81530b1b7f98.png)


**So the question arises.** 
First of all, I haven't modified any code and documents. 
Why can the other four corpuses run successfully while Wikipedia can't?

Thank you for your answer.

**Comment by LMY-nlp0701** [comment]
Hi !
I tried to explore why Wikipedia failed to run.

I made the following modifications to the code.
（data_gen/gen_test_train_data/gen_ace_msnbc_aquaint_csv.lua  **begin with line:182**）
![image](https://user-images.githubusercontent.com/33420219/48003713-2a66a680-e14a-11e8-9d36-3606007d7aaf.png)

Accordingly, I have annotated four other corpora.
![image](https://user-images.githubusercontent.com/33420219/48003769-5550fa80-e14a-11e8-9e87-e1f1e126f27e.png)


### **I just run gen_ace_msnbc_aquaint_csv.lua.**
Command: th data_gen/gen_test_train_data/gen_ace_msnbc_aquaint_csv.lua -root_data_dir data_path/
The experimental results are shown below.
![9ef8yjhwh p cg8vf3mizgp](https://user-images.githubusercontent.com/33420219/48004124-4dde2100-e14b-11e8-9729-671febd5d5ba.jpg)
![uif 7vw mhy 4p29jf3r](https://user-images.githubusercontent.com/33420219/48004149-5df60080-e14b-11e8-9a11-006ef6f2d20d.jpg)
![u10jdv bi hlavu3 dmfh3](https://user-images.githubusercontent.com/33420219/48004165-677f6880-e14b-11e8-8106-ce24ffde9686.jpg)
![olr4 _s_osmk xi4 jd31z3](https://user-images.githubusercontent.com/33420219/48004179-6f3f0d00-e14b-11e8-8fbe-c0519296c065.jpg)
![p6vh ax1qpaq j1_054y q](https://user-images.githubusercontent.com/33420219/48004186-7534ee00-e14b-11e8-9c01-96a14d3ae4a8.jpg)


Results show **Zielona_Góra_(parliamentary_constituency)** does not exist, but I am sure my corpus contains this document.
![image](https://user-images.githubusercontent.com/33420219/48004318-d52b9480-e14b-11e8-9fdd-e1b8ee9b07f1.png)


Thank you for your answer!

**Comment by LMY-nlp0701** [comment]
Hi ! I think I have solved this problem.
After my own step-by-step debugging, I found that there was no mistake in the program itself.
### The problem is the way to decompress **basic_data.zip** files.


**My previous operation**
1. Decompression in Windows environment.(Local)
2. Upload to server (Linux environment)

**The problem posed：**
Files with special characters (such as Rome characters) in the folder show exceptions.
The folder is basic_data/test_datasets/wned-datasets/wikipedia/RawText

So when you directly decompress on the server(Linux environment), you will not encounter such a bug.
I hope other people will take this as a warning.


**Finally, I would like to thank the author again for sharing this code, and also for the author's answer.**
**Thank you so much!**

**Comment by octavian-ganea** [comment]
Ah, nice catch! Thanks!
