### ISSUE TITLE
How do I generate textWithAnchorsFromAllWikipedia2014Feb.txt files?

### ISSUE THREAD

**Issue by LMY-nlp0701** [dalab/deep-ed#18]
Hi, Sorry to bother you again.

### **I want to generate Latest textWithAnchorsFromAllWikipedia documents**
I noticed that you provided **WikiExtractro.py** to generate the above documents.
![image](https://user-images.githubusercontent.com/33420219/48879256-db0cbf80-ee45-11e8-8bd6-a20c6a990790.png)

After reading the code, I want to ask how to get the input wiki file of the code, that is: **the wikipedia dump file**

![image](https://user-images.githubusercontent.com/33420219/48879347-40f94700-ee46-11e8-841d-72602d0b928e.png)

**What else should we pay attention to about the six parameters of the function?**

Thank you for your reply.
Thank you!

**Comment by octavian-ganea** [comment]
Hi. The textWithAnchorsFromAllWikipedia file was generated using https://github.com/attardi/wikiextractor and the --links option to preserve hyperlinks. Hope it helps.
