### ISSUE TITLE
persons.txt in basic data

### ISSUE THREAD

**Issue by zhaoluffy** [dalab/deep-ed#6]
Hi,
How did you get the file of "persons.txt" in basic data, if it is generated from wiki, could you share the idea?

**Comment by octavian-ganea** [comment]
Unfortunately, I do not have that code. But as far as I remember, an entity was categorized as a person if it contained a category of type 'YEAR births' or 'YEAR deaths'.

**Comment by zhaoluffy** [comment]
Thanks a lot. I've got the general idea
